version: 2

references:
  python36: &python36
    docker:
      - image: cimg/python:3.6
        environment:
          POETRY_VERSION: 1.1.6

  install_deps: &install_deps
    run:
      name: Install Python dependencies
      command: >-
        pip install -U pip==21.1 setuptools==56.0.0 wheel==0.36.2
        && curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        && poetry install --no-root

  store_python_version: &store_python_version
    run:
      name: Create python version cache key
      command: echo $PYTHON_VERSION > ~/project/.CIRCLECI_PYTHON_VERSION

  restore_cache: &restore_cache
    restore_cache:
      keys:
        # Find a cache corresponding to this specific poetry.lock checksum
        # when this file is changed, this key will fail
        - poetry-cache-{{ checksum ".CIRCLECI_PYTHON_VERSION" }}-{{ checksum "poetry.lock" }}
        # If it fails, use the most recently generated cache (to speed up pip installs)
        - poetry-cache-{{ checksum ".CIRCLECI_PYTHON_VERSION" }}-

  save_cache: &save_cache
    save_cache:
      key: poetry-cache-{{ checksum ".CIRCLECI_PYTHON_VERSION" }}-{{ checksum "poetry.lock" }}
      paths:
        - /home/circleci/.cache/pypoetry/virtualenvs

  test_library: &test_library
    run:
      name: Test
      command: poetry run python -m pytest

  test_defaults: &test_defaults
    steps:
      - checkout
      - *store_python_version
      - *restore_cache
      - *install_deps
      - *test_library
      - *save_cache

jobs:
  test_python39:
    <<: *test_defaults
    docker:
      - image: cimg/python:3.9
        environment:
          POETRY_VERSION: 1.1.6

  test_python38:
    <<: *test_defaults
    docker:
      - image: cimg/python:3.8
        environment:
          POETRY_VERSION: 1.1.6

  test_python37:
    <<: *test_defaults
    docker:
      - image: cimg/python:3.7
        environment:
          POETRY_VERSION: 1.1.6

  build_python36:
    <<: *python36
    steps:
      - checkout
      - *store_python_version
      - *restore_cache
      - *install_deps
      - *save_cache

  test_python36:
    <<: *python36
    steps:
      - checkout
      - *store_python_version
      - *restore_cache
      - run:
          name: Pytest and coverage report
          command: poetry run python -m pytest --cov=./business test --cov-report=html
      - store_artifacts:
          path: htmlcov

  lint:
    <<: *python36
    steps:
      - checkout
      - *store_python_version
      - *restore_cache
      - run:
          name: flake8 linter
          command: poetry run flake8 business test --statistics

  typecheck:
    <<: *python36
    steps:
      - checkout
      - *store_python_version
      - *restore_cache
      - run:
          name: MyPy typechecking
          command: poetry run mypy business

workflows:
  version: 2
  build:
    jobs:
      - test_python39
      - test_python38
      - test_python37
      - build_python36
      - test_python36:
          requires:
            - build_python36
      - lint:
          requires:
            - build_python36
      - typecheck:
          requires:
            - build_python36
